---
system:
  package_path: /tmp/packages
  packages:
    - "make"
    - "autoconf"
    - "gcc"
    - "bison"
    - "libxml2"
    - "libxml2-dev"
    - "curl"
    - "openssl"
    - "snmp"
    - "snmpd"
    - "snmp-mibs-downloader"
    - "libmcrypt-dev"
    - "libcurl4-gnutls-dev"
    - "libssl-dev"
    - "libjpeg-dev"
    - "libpng12-dev"
    - "libxpm-dev"
    - "libfreetype6-dev"
    - "libperl-dev"
    - "libtidy-dev"
    - "libxslt1-dev"
    - "pkg-config"
    - "libsslcommon2-dev"
    - "libbz2-dev"
    - "libgmp-dev"
    - "mariadb-server"
    - "libmysqlclient-dev"
    - "libpspell-dev"
    - "libpng-dev"
    - "libgmp3-dev"
    - "libmysqlclient-dev"
    - "librecode-dev"
    - "libldap-2.4-2"
    - "ldap-utils"
    - "libldap2-dev"
    - "libsnmp-dev"
    - "nodejs"
    - "python-pexpect"
    - "python-mysqldb"
    - "graphicsmagick"
    - "libjpeg-turbo-progs"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    - "pngnq"

nodejs:
  version: "v8.0.0"

nginx:
  version: "1.10.3"
  deb_filename: "nginx_1.10.3_amd64"
  default_config: "default.conf"

php:
  version: "7.1.1"
  source_file: "php-7.1.1.tar.gz"
  deb_filename: "php7.1.1-1-xenial"
  fpm_filename: "php-fpm_7.1-xenial"
  config_file: "php.ini"
  build_configure_command: "./buildconf --force"
  source_configure_command: >
    ./configure
    --prefix=/opt/php
    --with-config-file-path=/opt/php/conf
    --enable-fpm
    --with-fpm-user=vagrant
    --with-fpm-group=vagrant
    --enable-mbstring
    --enable-zip
    --enable-bcmath
    --enable-ftp
    --enable-exif
    --enable-calendar
    --enable-sysvmsg
    --enable-sysvsem
    --enable-sysvshm
    --enable-wddx
    --with-curl=/usr/bin
    --with-mcrypt
    --with-iconv-dir=/usr
    --with-pspell
    --with-gd
    --with-jpeg-dir=/usr
    --with-png-dir=/usr
    --with-zlib-dir=/usr
    --with-xpm-dir=/usr
    --with-freetype-dir=/usr
    --enable-gd-native-ttf
    --enable-gd-jis-conv
    --with-openssl
    --enable-mysqlnd
    --with-pdo-mysql=mysqlnd
    --with-mysqli=mysqlnd
    --with-mysql-sock
    --with-gettext=/usr
    --with-zlib=/usr
    --with-bz2=/usr
    --with-recode=/usr
    --with-tidy=/usr
    --with-xsl=/usr
    --with-ldap
    --with-xmlrpc
    --with-snmp=/usr
    --with-pear
    --with-libdir=/lib/x86_64-linux-gnu
    --enable-shmop
    --enable-maintainer-zts -enable-opcache
    --enable-sockets
    --with-snmp
    --enable-soap
    --enable-intl

mariadb:
  passwd: "something"

maven:
  major: 3
  version: 3.5.0
  home_parent_directory: /opt

tomcat:
  version: 8.0.23
  http_port: 8080
  ajp_port: 8009
  ipv6_disable: True
  jmx_registry_port: 10080
  jmx_server_port: 10081
  admin_username: admin
  admin_password: admin
  min_heap_size: 512M
  max_heap_size: 512M
  metaspace_size: 128M
  max_metaspace_size: 128M
  gc_log_file: /opt/tomcat/logs/gc.log
  heap_dump_dir: /opt/tomcat/logs/
