---
system:
    package_path: /tmp/packages

nginx:
    version: "1.10.3"
    deb_filename: "nginx_1.10.3_amd64"

php:
    version: "7.1.1"
    deb_filename: "php7.1.1-1-xenial"
    fpm_filename: "php-fpm_7.1-xenial"
