---
system:
  package_path: /tmp/packages
  packages:
    - "make"
    - "autoconf"
    - "gcc"
    - "bison"
    - "libxml2"
    - "libxml2-dev"
    - "curl"
    - "openssl"
    - "snmp"
    - "snmpd"
    - "snmp-mibs-downloader"
    - "libmcrypt-dev"
    - "libcurl4-gnutls-dev"
    - "libssl-dev"
    - "libjpeg-dev"
    - "libpng12-dev"
    - "libxpm-dev"
    - "libfreetype6-dev"
    - "libperl-dev"
    - "libtidy-dev"
    - "libxslt1-dev"
    - "pkg-config"
    - "libsslcommon2-dev"
    - "libbz2-dev"
    - "libgmp-dev"
    - "mariadb-server"
    - "libmysqlclient-dev"
    - "libpspell-dev"
    - "libpng-dev"
    - "libgmp3-dev"
    - "libmysqlclient-dev"
    - "librecode-dev"
    - "libldap-2.4-2"
    - "ldap-utils"
    - "libldap2-dev"
    - "libsnmp-dev"
    - "npm"
    - "nodejs-legacy"
    - "python-pexpect"
    - "graphicsmagick"
    - "libjpeg-turbo-progs"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    - "pngnq"

nodejs:
  version: "4.3.0"

nginx:
  version: "1.10.3"
  deb_filename: "nginx_1.10.3_amd64"
  default_config: "default.conf"

php:
  version: "7.1.1"
  source_file: "php-7.1.1.tar.gz"
  deb_filename: "php7.1.1-1-xenial"
  fpm_filename: "php-fpm_7.1-xenial"
  install_shell: "php_install.sh"
  config_file: "php.ini"

mariadb:
  passwd: "something"
