version: '2'
services:
  solr:
    image: solr
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - /mnt/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore