---
- name: Check if nginx is installed
  command: dpkg-query -W nginx
  register: nginx_deb_state
  failed_when: nginx_deb_state.rc > 1
  changed_when: nginx_deb_state.rc == 1

- name: Copy nginx deb package the the client
  copy:
    src: roles/base/files/{{nginx.deb_filename}}.deb
    dest: /tmp/packages
    owner: vagrant
    group: vagrant
    mode: 0755
  when: nginx_deb_state.rc == 1

- name: Install nginx package with dpkg
  apt: deb="/tmp/packages/{{nginx.deb_filename}}.deb"
  when: nginx_deb_state.rc == 1
  
- name: Ensure nginx service is started
  service:
    name: nginx
    state: restarted