---
# Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;
- name: python pip
  apt: pkg=python-pip state=installed

- name: python mysqldb
  apt: pkg=python-mysqldb state=installed

- name: Create a database
  become: true
  mysql_db: name={{ mysql_dbname }} state=present

- name: Create a dedicated user
  become: true
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} priv={{ mysql_dbname }}.*:ALL,GRANT state=present