---
- name: Check if mariadb is installed
  command: dpkg-query -W mariadb-server
  register: mariadb_deb_state
  failed_when: mariadb_deb_state.rc > 1
  changed_when: mariadb_deb_state.rc == 1

- name: install the package "mariadb-server"
  apt:
    name: mariadb-server
    state: latest
  when: mariadb_deb_state.rc == 1

- name: make sure mariadb service running
  service: name=mysql state=started