---
- name: Unzip the PHP source code file
  unarchive:
    src: roles/development/files/npm-4.3.0.tar.gz
    dest: /root/packages/

- name: Make install npm
  make:
    chdir: "{{ ansible_env.HOME}}/packages/npm-4.3.0/"
    target: install
