---
- name: Copy nginx configuration file into box
  template:
    src: nginx.conf
    dest: "/etc/nginx/"
    mode: 0644
  notify: Restart nginx

- name: Copy nginx file
  template:
    src: "{{nginx.default_config}}"
    dest: /etc/nginx/conf.d/{{ nginx_server_name }}.conf
    force: yes
  notify: Restart nginx

- name: Check if default nginx file exists
  stat:
    path: /etc/nginx/conf.d/default.conf
  register: nginx_default

- name: Delete default nginx file if it exists
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx

- name: Copy php-fpm config file
  copy:
        src: roles/development/files/php-fpm.conf
        dest: /opt/php/etc
        owner: root
        group: root
        mode: 0644
  notify: Restart nginx

- name: Copy www config file
  copy:
        src: roles/development/files/www.conf
        dest: /opt/php/etc/php-fpm.d
        owner: root
        group: root
        mode: 0644
  notify: Restart nginx

- name: Start php-fpm service
  command: php-fpm
  notify: Restart nginx