---
- name: Copy php-fpm config file
  copy:
        src: roles/development/files/php-fpm.conf
        dest: /opt/php/etc
        owner: root
        group: root
        mode: 0644

- name: Copy www config file
  copy:
        src: roles/development/files/www.conf
        dest: /opt/php/etc/php-fpm.d
        owner: root
        group: root
        mode: 0644

- name: Copy php-fpm start file
  copy:
        src: roles/development/files/php-fpm
        dest: /etc/init.d/php-fpm
        owner: root
        group: root
        mode: 0755

- name: Boot start php-fpm
  command: update-rc.d php-fpm defaults 01
  args:
      chdir: /etc/init.d

- name: Start php-fpm service
  command: php-fpm