---
- name: Create ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Update repositories cache and install the dependencies for PHP
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - openssl
    - python-openssl

- name: Generating ssl private key
  openssl_privatekey:
    path: /etc/nginx/ssl/privkey.pem

- name: Generating ssl public key
  openssl_publickey:
    path: /etc/nginx/ssl/public.pem
    privatekey_path: /etc/nginx/ssl/privkey.pem
    
- name: Copy nginx configuration file into box
  template:
    src: nginx.conf
    dest: "/etc/nginx/"
    mode: 0644
  notify: Restart nginx

- name: Copy nginx file
  template:
    src: "{{nginx.default_config}}"
    dest: /etc/nginx/conf.d/{{ nginx_server_name }}.conf
    force: yes
  notify: Restart nginx

- name: Check if default nginx file exists
  stat:
    path: /etc/nginx/conf.d/default.conf
  register: nginx_default

- name: Delete default nginx file if it exists
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx

- name: Copy php-fpm config file
  copy:
        src: roles/development/files/php-fpm.conf
        dest: /opt/php/etc
        owner: root
        group: root
        mode: 0644
  notify: Restart nginx

- name: Copy www config file
  copy:
        src: roles/development/files/www.conf
        dest: /opt/php/etc/php-fpm.d
        owner: root
        group: root
        mode: 0644
  notify: Restart nginx

- name: Start php-fpm service
  command: php-fpm
  notify: Restart nginx