---
- name: Copy php-fpm config file
  copy:
        src: roles/development/files/php-fpm.conf
        dest: /opt/php/etc
        owner: root
        group: root
        mode: 0644

- name: Delete www.conf
  become: yes
  file: path=/opt/php/etc/php-fpm.d/www.conf state=absent

- name: Copy magento2.conf
  become: yes
  copy: src=magento2.conf dest=/opt/php/etc/php-fpm.d/magento2.conf

#- name: Restart php-fpm service
#  command: php-fpm