---
#@todo Check if xdebug is installed
- name: Unzip the PHP source code file
  unarchive:
    src: roles/development/files/xdebug-2.5.0.tgz
    dest: /root/packages/
    creates: xdebug.source.lock

- name: Phpize xdebug
  shell: phpize && ./configure --enable-xdebug
  args:
    chdir: "{{ ansible_env.HOME}}/packages/xdebug-2.5.0/"
  register: xdebug_config

- name: Make install xdebug
  make:
    chdir: "{{ ansible_env.HOME}}/packages/xdebug-2.5.0/"
    target: install
  when: xdebug_config.rc == 0

#@todo Use xdebug_config.stdout_lines to read the xdebug.so file path
- name: Copy php.ini file
  copy:
      src: roles/development/files/{{php.config_file}}
      dest: /opt/php/conf/php.ini
      force: yes