---
#- name: Set repo.magento.com composer keys
#  shell: composer config --global http-basic.repo.magento.com {{ magento_account_public_key }} {{ magento_account_private_key }}
- name: Repos directory
  become: yes
  file: path=/home/vagrant/repos/ state=directory owner=vagrant group=vagrant

- name: Copy magento2
  unarchive:
    src: magento2.tar.gz
    dest: /home/vagrant/repos/
    owner: vagrant
    group: vagrant

- name: Install MariaDB packages
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - mariadb-server-10.0
    - mariadb-client-10.0
    - python-mysqldb

- name: Create a database
  become: true
  mysql_db: name={{ mysql_dbname }} state=present

- name: Create a dedicated user
  become: true
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} priv={{ mysql_dbname }}.*:ALL,GRANT state=present
