---
- name: Check if nginx is installed
  command: dpkg-query -W nginx
  register: nginx_deb_state
  failed_when: nginx_deb_state.rc > 1
  changed_when: nginx_deb_state.rc == 1

- name: Copy nginx deb package the the client
  copy:
    src: roles/base/files/{{nginx.deb_filename}}.deb
    dest: "{{ ansible_env.HOME}}/packages/"
    owner: vagrant
    group: vagrant
    mode: 0755
  when: nginx_deb_state.rc == 1

- name: Install nginx package with dpkg
  apt: deb="{{ ansible_env.HOME}}/packages/{{nginx.deb_filename}}.deb"
  when: nginx_deb_state.rc == 1
  
- name: Repos directory
  become: yes
  file: path={{ item }} state=directory owner=root group=root
  with_items:
    - /etc/nginx/sites-available/
    
- name: Copy nginx file
  copy: src=magento2.conf dest=/etc/nginx/sites-available/magento2.conf
  
- name: Disable default site
  become: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Enable magento2 site
  become: yes
  file: src=/etc/nginx/sites-available/magento2.conf dest=/etc/nginx/conf.d/magento2.conf state=link

- name: Ensure nginx service is started
  service:
    name: nginx
    state: restarted
