---
- name: Check if nginx is installed
  command: dpkg-query -W nginx
  register: nginx_deb_state
  failed_when: nginx_deb_state.rc > 1
  changed_when: nginx_deb_state.rc == 1

- name: Copy nginx deb package the the client
  copy:
    src: roles/base/files/{{nginx.deb_filename}}.deb
    dest: "{{ ansible_env.HOME}}/packages/"
    mode: 0755
  when: nginx_deb_state.rc == 1

- name: Install nginx package with dpkg
  apt:
    deb: "{{ ansible_env.HOME}}/packages/{{nginx.deb_filename}}.deb"
  when: nginx_deb_state.rc == 1
