---
- name: Check if php is installed
  command: dpkg-query -W php7.1
  register: php_deb_state
  failed_when: php_deb_state.rc > 1
  changed_when: php_deb_state.rc == 1

- name: Make directory in HOME for php source code
  file:
    path: "{{ ansible_env.HOME}}/php-src"
    state: directory
    mode: 0755

- name: Unzip the PHP source code file
  unarchive:
    src: roles/base/files/{{php.source_file}}
    dest: "{{ ansible_env.HOME}}/php-src"
    creates: php.source.lock

- name: Install php
  script:  "roles/base/files/{{php.install_shell}}"
  args:
    creates: php.install.lock

- name: Copy nginx-php file
  copy:
    src: roles/base/files/default.conf
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 0644

- name: Restart nginx service
  service:
    name: nginx
    state: restarted