---
# @todo If we need to remove the lock
#    sudo rm /var/cache/apt/archives/lock
#    sudo rm /var/lib/dpkg/lock
#    sudo rm /var/lib/apt/lists/lock
- name: Update repositories cache and install the dependencies for PHP
  apt: name={{item}} state=installed update_cache=yes
  with_items: "{{system.packages}}"

- name: Check npm verison
  command: npm -v
  register: npm_version

- name: Install the specified npm version
  command: npm install -g npm@{{nodejs.version}}
  register: npm_install
  when: npm_version.stdout != "{{nodejs.version}}"

- name: Create symlink to installed npm
  file:
    src: /usr/local/lib/node_modules/npm/bin/npm-cli.js
    dest: /usr/bin/npm
    state: link
    force: yes
  when:
    - not npm_install|skipped
    - npm_install|succeeded
    
- name: Make directory in /tmp for temporary uploads files
  file:
    path: "{{ ansible_env.HOME}}/packages"
    state: directory
    mode: 0755