---
- name: Remove the lock
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock
    - /var/lib/apt/lists/lock

- name: Reconfigure packages
  command: dpkg --configure -a

- name: Add node.js v8.x repository
  shell:  "curl -sL https://deb.nodesource.com/setup_8.x | bash -"
  register: node_source
  failed_when: node_source.rc != 0

- name: Make directory in /tmp for temporary uploads files
  file:
    path: "{{ ansible_env.HOME}}/packages"
    state: directory
    mode: 0755

- name: Update repositories cache and install the dependencies for PHP
  apt: name={{item}} update_cache=yes
  with_items: "{{system.packages}}"
