---
- name: Remove the lock
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock
    - /var/lib/apt/lists/lock

- name: Reconfigure packages
  command: dpkg --configure -a

- name: Update repositories cache and install basic package
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items: "{{packages.basic}}"
  tags:
    - packages

- name: Install the packages that is required by ansible
  apt:
    name: "{{item}}"
  with_items: "{{packages.ansible}}"
  tags:
    - packages

- name: Make directory in /tmp for temporary uploads files
  file:
    path: "{{ ansible_env.HOME}}/packages"
    state: directory
    mode: 0755
